django-jquery-file-uploader/urls.py
from django.conf.urls import include, url
from django.http import HttpResponseRedirect
from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = [
    url(r'^', include('jqfuploader.urls')),
    url(r'^admin/', include(admin.site.urls)),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jqfuploader/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from .views import index, UploadView, delete

app_name="jqfuploader"

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^upload/$', UploadView.as_view(), name='upload'),
    url(r'^delete/(?P<uid>[0-9a-fA-F]+)$', delete, name='delete'),
]

jqfuploader/models.py
import hashlib
import os
import uuid

from django.db import models
from django.dispatch import receiver
from django.db.models.signals import post_delete

def generate_file_path(instance, filename):
    return os.path.join(instance.dataset.name, filename)

class UploadFileBase(models.Model):
    file = models.FileField(blank=True, upload_to=generate_file_path)
    file_name = models.CharField(max_length=255)
    total_size = models.BigIntegerField(default=0)
    recorded_size = models.BigIntegerField(default=0)
    recorded_md5 = models.CharField(max_length=32, blank=True)
    unique_id = models.UUIDField(default=uuid.uuid4, editable=False)

    @property
    def current_size(self):
        return self.file.size

    @property
    def md5(self):
        md5 = hashlib.md5()
        close_after = False

        if self.file.closed:
            self.file.open('rb')
            close_after = True

        for chunk in self.file.chunks():
            md5.update(chunk)

        if close_after:
            self.close_file()

        return md5.hexdigest()

    @property
    def is_finished(self):
        return self.total_size == self.recorded_size

    class Meta:
        abstract = True
        unique_together = (('file_name', 'total_size'),)

    def __str__(self):
        return 'name: {file_name}; size: {total_size}; md5: {recorded_md5}; uid: {unique_id}'.format(
            file_name=self.file_name,
            total_size=self.total_size,
            recorded_md5=self.recorded_md5,
            unique_id=self.unique_id
        )

    def close_file(self):
        """
        Bug in django 1.4: FieldFile `close` method is not reaching all the
        way to the actual python file.
        Fix: we had to loop all inner files and close them manually.
        """
        file_ = self.file
        while file_ is not None:
            file_.close()
            file_ = getattr(file_, 'file', None)

    def delete_file(self):
        print('removing ' + self.file.path)
        os.remove(self.file.path)

    def append_chunk(self, chunk, mode='ab'):
        self.close_file()
        self.file.open(mode=mode)
        self.file.write(chunk.read())
        self.recorded_size = self.current_size
        self.close_file()

class DataSet(models.Model):
    name = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.name

class UploadFile(UploadFileBase):
    dataset = models.ForeignKey(DataSet)

    class Meta:
        unique_together = (('dataset', 'unique_id'), ('dataset', 'file_name', 'total_size'))

# These two auto-delete files from filesystem when they are unneeded:
@receiver(post_delete, sender=UploadFile)
def auto_delete_file_on_delete(sender, instance, **kwargs):
    """Deletes file from filesystem
    when corresponding `UploadFileBase` object is deleted.
    """
    print('removing ' + instance.file.path)
    if instance.file:
        os.remove(instance.file.path)

class UploadSettings(models.Model):
    enable_upload = models.BooleanField(default=True)
    max_upload_size = models.IntegerField(default=999000000)
    max_chunk_size = models.IntegerField(default=1000000)
    allowed_types = models.TextField(default='/(\.|\/)(gif|jpe?g|png|mp4)$/i')
    page_title = models.CharField(max_length=100, default="jQuery File Upload")
    page_notes = models.TextField(),
    notification_email = models.TextField(),

jqfuploader/views.py
# -*- encoding: utf-8 -*-
import re

from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect

from django.core.mail import send_mail
from django.core.files.base import ContentFile
from django.views.generic import View, TemplateView

from .models import DataSet, UploadFile, UploadSettings
from .responses import UploadResponse, UploadError, UploadFinished

# Create your views here.
def index(request):
    try:
        set = UploadSettings.objects.get(enable_upload=True)
    except UploadSettings.DoesNotExist:
        return HttpResponse('Sorry, no upload allowed. <a href="/">Go to the main page</a>')
    except UploadSettings.MultipleObjectsReturned:
        setlist = UploadSettings.objects.filter(enable_upload=True)
        set = setlist[0];

    context = { 'settings' : set }
    return render(
        request,
        'jqfuploader/index.html',
        context
    )

class UploadBaseView(View):
    model = UploadFile
    field_name = 'files'
    content_range_header = 'HTTP_CONTENT_RANGE'
    content_range_pattern = re.compile(
        r'^bytes (?P<start>\d+)-(?P<end>\d+)/(?P<total>\d+)$'
    )

    def get_content_range(self, request, chunk):
        content_range = request.META.get(self.content_range_header)
        if content_range is not None:
            match = self.content_range_pattern.match(content_range)
            if match:
                start = int(match.group('start'))
                end = int(match.group('end'))
                total = int(match.group('total'))
            else:
                raise UploadError(message='The Content Range header seems wrong.', status=400)
            if end - start + 1 != chunk.size:
                raise UploadFile(message='The chunk size don\'t match the header.', status=400)
        else:
            start = 0
            end = chunk.size - 1
            total = chunk.size
        return start, end, total

    @staticmethod
    def get_or_create_dataset(name):
        try:
            dataset = DataSet.objects.get(name=name)
        except DataSet.DoesNotExist:
            dataset = DataSet(name=name)
            dataset.save()
        return dataset

    def get_or_create_chunked_upload(self, name, total_size, dataset):
        try:
            chunked_upload = self.model.objects.get(file_name=name, total_size=total_size, dataset=dataset)
        except self.model.DoesNotExist:
            empty_chunk = ContentFile(name=name, content='')
            chunked_upload = self.model(file=empty_chunk, file_name=name, total_size=total_size, dataset=dataset)
            chunked_upload.recorded_md5 = 0;
            chunked_upload.recorded_size = 0;
            chunked_upload.save()
        except self.model.MultipleObjectsReturned:
            chunked_uploads = self.model.objects.filter(file_name=chunk.name, total_size=total_size, dataset=dataset)
            map(lambda x: x.delete(), chunked_uploads[1:])
            chunked_upload = chunked_uploads[0]
        return chunked_upload

    def _post(self, request):
        raise NotImplementedError("You have to define this method in children View class")

    def post(self, request):
        try:
            return self._post(request)
        except UploadError as error:
            return UploadResponse(error.data, status=error.status)
        except Exception as error:
            return UploadResponse({'message': error.__str__()}, status=500)

class UploadView(UploadBaseView):
    def _post(self, request):
        chunk = request.FILES.get(self.field_name)
        start, end, total = self.get_content_range(request, chunk)
        file_name = chunk._get_name();
        dataset_name = request.POST.get('dataset_name')
        if dataset_name == None:
            dataset_name = "dsname_%s" % re.sub('[.\ ]', '_', file_name)
        dataset = self.get_or_create_dataset(dataset_name)
        chunked_upload = self.get_or_create_chunked_upload(chunk.name, total, dataset)
        if chunked_upload.is_finished:
            return UploadFinished(chunked_upload)
        else:
            if start == 0:
                chunked_upload.append_chunk(chunk, mode='wb')
            else:
                if chunked_upload.current_size == start:
                    chunked_upload.append_chunk(chunk)
                else:
                    raise UploadError(
                        message='Upload content\'s start don\'t '
                                'equal to the file current size',
                        status=400
                    )
            chunked_upload.save()

        if chunked_upload.is_finished:
            chunked_upload.recorded_md5 = chunked_upload.md5

            try:
                set = UploadSettings.objects.get(enable_upload=True)
            except UploadSettings.DoesNotExist:
                return UploadFinished(chunked_upload)
            except UploadSettings.MultipleObjectsReturned:
                setlist = UploadSettings.objects.filter(enable_upload=True)
                set = setlist[0];

            msg = "File %s: size: %d b\n%s" % ("", 0, "")
            send_mail(
                subject="File uploaded",
                message=msg,
                from_email=set.notification_email,
                recipient_list=[set.notification_email]
            )
            return UploadFinished(chunked_upload)

        return UploadFinished(chunked_upload)
        #return UploadResponse({'status': 'success'}, status=202)

def delete(request, uid):
        try:
            file = UploadFile.objects.get(unique_id=uid)
            file.delete_file()
            file.delete()
        except UploadFile.DoesNotExist:
            pass

        return UploadResponse({'status': 'success'}, status=202)

jqfuploader/templates/jqfuploader/index.html
{% load static %}

<!DOCTYPE HTML>
<!--
/*
 * jQuery File Upload Plugin Demo
 * https://github.com/blueimp/jQuery-File-Upload
 *
 * Copyright 2010, Sebastian Tschan
 * https://blueimp.net
 *
 * Licensed under the MIT license:
 * https://opensource.org/licenses/MIT
 */
-->
<html lang="en">
<head>
<!-- Force latest IE rendering engine or ChromeFrame if installed -->
<!--[if IE]>
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<![endif]-->
<meta charset="utf-8">
<title>{{ settings.page_title }}</title>
<meta name="description" content="File Uploader.">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<!-- Bootstrap styles -->
<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<!-- Generic page styles -->
<link rel="stylesheet" href="{% static 'jqfuploader/css/style.css' %}">
<!-- blueimp Gallery styles -->
<link rel="stylesheet" href="//blueimp.github.io/Gallery/css/blueimp-gallery.min.css">
<!-- CSS to style the file input field as button and adjust the Bootstrap progress bars -->
<link rel="stylesheet" href="{% static 'jqfuploader/css/jquery.fileupload.css' %}">
<link rel="stylesheet" href="{% static 'jqfuploader/css/jquery.fileupload-ui.css' %}">
<!-- CSS adjustments for browsers with JavaScript disabled -->
<noscript><link rel="stylesheet" href="{% static 'jqfuploader/css/jquery.fileupload-noscript.css' %}"></noscript>
<noscript><link rel="stylesheet" href="{% static 'jqfuploader/css/jquery.fileupload-ui-noscript.css' %}"></noscript>
</head>
<body>
<div class="container">
    <h1>{{ settings.page_title }}</h1>
<!--     <h2 class="lead">Basic Plus version</h2> -->
    <!-- The file upload form used as target for the file upload widget -->
    <form id="fileupload" action="//jquery-file-upload.appspot.com/" method="POST" enctype="multipart/form-data">
        <!-- Redirect browsers with JavaScript disabled to the origin page -->
        <noscript><input type="hidden" name="redirect" value="https://blueimp.github.io/jQuery-File-Upload/"></noscript>
        <!-- The fileupload-buttonbar contains buttons to add/delete files and start/cancel the upload -->
        <div class="row fileupload-buttonbar">
            <div class="col-lg-7">
                <!-- The fileinput-button span is used to style the file input field as button -->
                <span class="btn btn-success fileinput-button">
                    <i class="glyphicon glyphicon-plus"></i>
                    <span>Add files...</span>
                    <input type="file" name="files" multiple>
                </span>
                <button type="submit" class="btn btn-primary start">
                    <i class="glyphicon glyphicon-upload"></i>
                    <span>Start upload</span>
                </button>
                <button type="reset" class="btn btn-warning cancel">
                    <i class="glyphicon glyphicon-ban-circle"></i>
                    <span>Cancel upload</span>
                </button>
                <button type="button" class="btn btn-danger delete">
                    <i class="glyphicon glyphicon-trash"></i>
                    <span>Delete</span>
                </button>
                <input type="checkbox" class="toggle">
                <!-- The global file processing state -->
                <span class="fileupload-process"></span>
            </div>
            <!-- The global progress state -->
            <div class="col-lg-5 fileupload-progress fade">
                <!-- The global progress bar -->
                <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100">
                    <div class="progress-bar progress-bar-success" style="width:0%;"></div>
                </div>
                <!-- The extended global progress state -->
                <div class="progress-extended">&nbsp;</div>
            </div>
        </div>
        <!-- The table listing the files available for upload/download -->
        <table role="presentation" class="table table-striped"><tbody class="files"></tbody></table>
	<input id="dataset_name" type="input" name="dataset_name" value="upload" hidden/>
    </form>
    <br>
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Demo Notes</h3>
        <div class="panel-body">
            <ul>
                <li>The maximum file size for uploads is <strong>{{ settings.max_upload_size }} B</strong></li>
                <li>Only image files (<strong>JPG, GIF, PNG</strong>) are allowed in this demo (by default there is no file type restriction).</li>
                <li>You can <strong>drag &amp; drop</strong> files from your desktop on this webpage (see <a href="https://github.com/blueimp/jQuery-File-Upload/wiki/Browser-support">Browser support</a>).</li>
                <li>Please refer to the <a href="https://github.com/blueimp/jQuery-File-Upload">project website</a> and <a href="https://github.com/blueimp/jQuery-File-Upload/wiki">documentation</a> for more information.</li>
                <li>Built with the <a href="http://getbootstrap.com/">Bootstrap</a> CSS framework and Icons from <a href="http://glyphicons.com/">Glyphicons</a>.</li>
                {{ settings.page_notes }}
            </ul>
        </div>
        </div>
    </div>
</div>
<!-- The blueimp Gallery widget -->
<div id="blueimp-gallery" class="blueimp-gallery blueimp-gallery-controls" data-filter=":even">
    <div class="slides"></div>
    <h3 class="title"></h3>
    <a class="prev">‹</a>
    <a class="next">›</a>
    <a class="close">×</a>
    <a class="play-pause"></a>
    <ol class="indicator"></ol>
</div>
<!-- The template to display files available for upload -->
{% verbatim %}
<script id="template-upload" type="text/x-tmpl">
{% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-upload fade">
        <td>
            <span class="preview"></span>
        </td>
        <td>
            <p class="name">{%=file.name%}</p>
            <strong class="error text-danger"></strong>
        </td>
        <td>
            <p class="size">Processing...</p>
            <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><div class="progress-bar progress-bar-success" style="width:0%;"></div></div>
        </td>
        <td>
            {% if (!i && !o.options.autoUpload) { %}
                <button class="btn btn-primary start" disabled>
                    <i class="glyphicon glyphicon-upload"></i>
                    <span>Start</span>
                </button>
            {% } %}
            {% if (!i) { %}
                <button class="btn btn-warning cancel">
                    <i class="glyphicon glyphicon-ban-circle"></i>
                    <span>Cancel</span>
                </button>
            {% } %}
        </td>
    </tr>
{% } %}
</script>
<!-- The template to display files available for download -->
<script id="template-download" type="text/x-tmpl">
{% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-download fade">
        <td>
            <span class="preview">
                {% if (file.thumbnailUrl) { %}
                    <a href="{%=file.url%}" title="{%=file.name%}" download="{%=file.name%}" data-gallery><img src="{%=file.thumbnailUrl%}"></a>
                {% } %}
            </span>
        </td>
        <td>
            <p class="name">
                {% if (file.url) { %}
                    <a href="{%=file.url%}" title="{%=file.name%}" download="{%=file.name%}" {%=file.thumbnailUrl?'data-gallery':''%}>{%=file.name%}</a>
                {% } else { %}
                    <span>{%=file.name%}</span>
                {% } %}
            </p>
            {% if (file.error) { %}
                <div><span class="label label-danger">Error</span> {%=file.error%}</div>
            {% } %}
        </td>
        <td>
            <span class="size">{%=o.formatFileSize(file.size)%}</span>
        </td>
        <td>
            {% if (file.deleteUrl) { %}
                <button class="btn btn-danger delete" data-type="{%=file.deleteType%}" data-url="{%=file.deleteUrl%}"{% if (file.deleteWithCredentials) { %} data-xhr-fields='{"withCredentials":true}'{% } %}>
                    <i class="glyphicon glyphicon-trash"></i>
                    <span>Delete</span>
                </button>
                <input type="checkbox" name="delete" value="1" class="toggle">
            {% } else { %}
                <button class="btn btn-warning cancel">
                    <i class="glyphicon glyphicon-ban-circle"></i>
                    <span>Cancel</span>
                </button>
            {% } %}
        </td>
    </tr>
{% } %}
</script>
{% endverbatim %}
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<!-- The jQuery UI widget factory, can be omitted if jQuery UI is already included -->
<script src="{% static 'jqfuploader/js/vendor/jquery.ui.widget.js' %}"></script>
<!-- The Templates plugin is included to render the upload/download listings -->
<script src="//blueimp.github.io/JavaScript-Templates/js/tmpl.min.js"></script>
<!-- The Load Image plugin is included for the preview images and image resizing functionality -->
<script src="//blueimp.github.io/JavaScript-Load-Image/js/load-image.all.min.js"></script>
<!-- The Canvas to Blob plugin is included for image resizing functionality -->
<script src="//blueimp.github.io/JavaScript-Canvas-to-Blob/js/canvas-to-blob.min.js"></script>
<!-- Bootstrap JS is not required, but included for the responsive demo navigation -->
<script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
<!-- blueimp Gallery script -->
<script src="//blueimp.github.io/Gallery/js/jquery.blueimp-gallery.min.js"></script>
<!-- The Iframe Transport is required for browsers without support for XHR file uploads -->
<script src="{% static 'jqfuploader/js/jquery.iframe-transport.js' %}"></script>
<!-- The basic File Upload plugin -->
<script src="{% static 'jqfuploader/js/jquery.fileupload.js' %}"></script>
<!-- The File Upload processing plugin -->
<script src="{% static 'jqfuploader/js/jquery.fileupload-process.js' %}"></script>
<!-- The File Upload image preview & resize plugin -->
<script src="{% static 'jqfuploader/js/jquery.fileupload-image.js' %}"></script>
<!-- The File Upload audio preview plugin -->
<script src="{% static 'jqfuploader/js/jquery.fileupload-audio.js' %}"></script>
<!-- The File Upload video preview plugin -->
<script src="{% static 'jqfuploader/js/jquery.fileupload-video.js' %}"></script>
<!-- The File Upload validation plugin -->
<script src="{% static 'jqfuploader/js/jquery.fileupload-validate.js' %}"></script>
<!-- The MD5 function -->
<script src="{% static 'jqfuploader/js/spark-md5.min.js' %}"></script>
<script>
/*jslint unparam: true, regexp: true */
/*global window, $ */
$(function () {
    'use strict';

    // Enable iframe cross-domain access via redirect option:
//     $('#fileupload').fileupload(
//         'option',
//         'redirect',
//     );

    // Initialize the jQuery File Upload widget:
    $('#fileupload').fileupload({
        // Uncomment the following to send cross-domain cookies:
        //xhrFields: {withCredentials: true},
        url: '{% url 'jqfuploader:upload' %}',
        dataType: 'json',
        autoUpload: false,
        acceptFileTypes: {{ settings.allowed_types }},
        fieldName: 'files',
        maxFileSize: {{ settings.max_upload_size }},
        maxChunkSize: {{ settings.max_chunk_size }},
        // Enable image resizing, except for Android and Opera,
        // which actually support image resizing, but fail to
        // send Blob objects via XHR requests:
        disableImageResize: /Android(?!.*Chrome)|Opera/
            .test(window.navigator.userAgent),
        previewMaxWidth: 100,
        previewMaxHeight: 100,
        previewCrop: true,
        formData: function(form) {
            var sa = form.serializeArray();
            sa.push({ 'name' : 'csrfmiddlewaretoken', 'value' : getCookie('csrftoken')} );
            return sa;
        }
    });
});
</script>
<!-- The File Upload user interface plugin -->
<script src="{% static 'jqfuploader/js/jquery.fileupload-ui.js' %}"></script>
<!-- The main application script -->
<script src="{% static 'jqfuploader/js/md5.js' %}"></script>
<script src="{% static 'jqfuploader/js/csrf.js' %}"></script>
<!-- The XDomainRequest Transport is included for cross-domain file deletion for IE 8 and IE 9 -->
<!--[if (gte IE 8)&(lt IE 10)]>
<script src="js/cors/jquery.xdr-transport.js"></script>
<![endif]-->
</body>
</html>